
# config_backup.txt — ESG GPT 問答系統設定檔（純文字版備份）

[flow]
allow_jump = false
allow_backtrack = false
default_stage = initial
show_followup_suggestions = true

[question]
default_industry = retail
data_path = data/
csv_encoding = utf-8
required_fields = id, section, text, options, explanation, followups, level, industry_tag

[answers]
save_path = userdata/answers/
save_format = json
enable_versioning = true

[model]
provider = openai
use_rag = true
base_model = gpt-3.5-turbo
max_tokens = 800
temperature = 0.7
system_prompt_path = config/system_prompt.txt

[rag]
enable = true
index_path = knowledge_vector_db/index.faiss
chunk_size = 300
chunk_overlap = 30
retriever_top_k = 3
embedding_model = text-embedding-3-small

[report]
initial_length = 500
advanced_length = 1000
format = text
show_version_label = true

[ui]
show_progress_bar = true
allow_collapsible_sidebar = true
fixed_question_area = true
show_illustrations = true
enable_dark_mode = false

[topic]
enable_metadata = true
metadata_path = data/metadata.json
